name: Publish Crate
on:
    release:
        types: [published]
jobs:
    publish:
        runs-on: ubuntu-latest
        name: Publish
        steps:
            - uses: actions/checkout@v4
            - name: Install libudev-dev and pkg-config
              run: |
                sudo apt update
                sudo apt install -y libudev-dev pkg-config

            - uses: dtolnay/rust-toolchain@stable
              with:
                toolchain: nightly
            - uses: katyo/publish-crates@v2
              with:
                args: --allow-dirty
                registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
